
-- [그림 8-2 결과]
SELECT *
FROM MYDATA.DATASET4 LIMIT 10;

-- [그림 8-3 결과]
SELECT COUNT(PASSENGERID) N_PASSENGERS,
COUNT(DISTINCT PASSENGERID) N_D_PASSENGERS
FROM MYDATA.DATASET4;

-- [그림 8-4 결과]
SELECT SEX,
COUNT(PASSENGERID) N_PASSENGERS,
SUM(SURVIVED) N_SURVIVED
FROM MYDATA.DATASET4
GROUP
BY 1
;

-- [그림 8-5 결과]
SELECT SEX,
COUNT(PASSENGERID) N_PASSENGERS,
SUM(SURVIVED) N_SURVIVED,
SUM(SURVIVED)/ COUNT(PASSENGERID) SURVIVED_RATIO
FROM MYDATA.DATASET4
GROUP
BY 1
;

-- [그림 8-6 결과]
SELECT FLOOR(AGE/10)*10 AGEBAND,
AGE
FROM MYDATA.DATASET4
;

-- [그림 8-7 결과]
SELECT FLOOR(AGE/10)*10 AGEBAND,
COUNT(PASSENGERID) N_PASSENGERS,
SUM(SURVIVED) N_SURVIVED,
SUM(SURVIVED)/COUNT(PASSENGERID) SURVIVED_RATE
FROM MYDATA.DATASET4
GROUP
BY 1
;

-- [그림 8-8 결과]
SELECT FLOOR(AGE/10)*10 AGEBAND,
COUNT(PASSENGERID) N_PASSENGERS,
SUM(SURVIVED) N_SURVIVED,
SUM(SURVIVED)/COUNT(PASSENGERID) SURVIVED_RATE
FROM MYDATA.DATASET4
GROUP
BY 1
ORDER
BY 1
;

-- [그림 8-9 결과]
SELECT FLOOR(AGE/10)*10 AGEBAND,
SEX,
COUNT(PASSENGERID) N_PASSENGERS,
SUM(SURVIVED) N_SURVIVED,
SUM(SURVIVED)/COUNT(PASSENGERID) SURVIVED_RATE
FROM MYDATA.DATASET4
GROUP
BY 1,2
ORDER
BY 2,1
;

-- [그림 8-10 결과]
SELECT FLOOR(AGE/10)*10 AGEBAND,
SEX,
COUNT(PASSENGERID) N_PASSENGERS,
SUM(SURVIVED) N_SURVIVED,
SUM(SURVIVED)/COUNT(PASSENGERID) SURVIVED_RATE
FROM MYDATA.DATASET4
GROUP
BY 1,2
HAVING SEX = 'male'
;

-- [그림 8-11 결과]
SELECT FLOOR(AGE/10)*10 AGEBAND,
SEX,
COUNT(PASSENGERID) N_PASSENGERS,
SUM(SURVIVED) N_SURVIVED,
SUM(SURVIVED)/COUNT(PASSENGERID) SURVIVED_RATE
FROM MYDATA.DATASET4
GROUP
BY 1,2
HAVING SEX = 'female'
;

-- [그림 8-12 결과]
SELECT A.AGEBAND,
A.SURVIVED_RATE MALE_SURVIVED_RATE,
B.SURVIVED_RATE FEMALE_SURVIVED_RATE,
B.SURVIVED_RATE - A.SURVIVED_RATE SURVIVED_RATE_DIFF
FROM
(SELECT FLOOR(AGE/10)*10 AGEBAND,
SEX,
COUNT(PASSENGERID) N_PASSENGERS,
SUM(SURVIVED) N_SURVIVED,
SUM(SURVIVED)/COUNT(PASSENGERID) SURVIVED_RATE
FROM MYDATA.DATASET4
GROUP
BY 1,2
HAVING SEX = 'male') A
LEFT
JOIN
(SELECT FLOOR(AGE/10)*10 AGEBAND,
SEX,
COUNT(PASSENGERID) N_PASSENGERS,
SUM(SURVIVED) N_SURVIVED,
SUM(SURVIVED)/COUNT(PASSENGERID) SURVIVED_RATE
FROM MYDATA.DATASET4
GROUP
BY 1,2
HAVING SEX = 'female') B
ON A.AGEBAND = B.AGEBAND
ORDER
BY A.AGEBAND
;

-- [그림 8-14]
SELECT DISTINCT PCLASS
FROM MYDATA.DATASET4
;

-- [그림 8-16 결과]
SELECT PCLASS,
COUNT(PASSENGERID) N_PASSENGERS,
SUM(SURVIVED) N_SURVIVED,
SUM(SURVIVED)/COUNT(PASSENGERID) SURVIVED_RATE
FROM MYDATA.DATASET4
GROUP
BY PCLASS
ORDER
BY 1
;

-- [그림 8-17 결과]
SELECT PCLASS,
SEX,
COUNT(PASSENGERID) N_PASSENGERS,
SUM(SURVIVED) N_SURVIVED,
SUM(SURVIVED)/COUNT(PASSENGERID) SURVIVED_RATE
FROM MYDATA.DATASET4
GROUP
BY PCLASS,SEX
ORDER
BY 2,1
;

-- [그림 8-18 결과]
SELECT PCLASS,
SEX,
FLOOR(AGE/10)*10 AGEBAND,
COUNT(PASSENGERID) N_PASSENGERS,
SUM(SURVIVED) N_SURVIVED,
SUM(SURVIVED)/COUNT(PASSENGERID) SURVIVED_RATE
FROM MYDATA.DATASET4
GROUP
BY PCLASS,SEX, FLOOR(AGE/10)*10
ORDER
BY 2,1
;

-- [그림 8-19 결과]
SELECT EMBARKED,
COUNT(PASSENGERID) N_PASSENGERS
FROM MYDATA.DATASET4
GROUP
BY 1
ORDER
BY 1
;

-- [그림 8-20 결과]
SELECT EMBARKED,
SEX,
COUNT(PASSENGERID) N_PASSENGERS
FROM MYDATA.DATASET4
GROUP
BY 1,2
ORDER
BY 1,2
;

-- [261 페이지, 승선 항구별 전체 승객 수]
SELECT EMBARKED,
COUNT(PASSENGERID) N_PASSENGERS
FROM MYDATA.DATASET4
GROUP
BY 1
;

-- [261 페이지, 승선 항구별, 성별 승객 수]
SELECT EMBARKED,
SEX,
COUNT(PASSENGERID) N_PASSENGERS
FROM MYDATA.DATASET4
GROUP
BY 1,2
;

-- [262 페이지, 테이블 결합]
SELECT A.EMBARKED,
A.SEX,
A.N_PASSENGERS,
B.N_PASSENGERS N_PASSENGERS_TOT,
A.N_PASSENGERS/B.N_PASSENGERS PASSENGERS_RAT
FROM
(SELECT EMBARKED,
SEX,
COUNT(PASSENGERID) N_PASSENGERS
FROM MYDATA.DATASET4
GROUP
BY 1,2) A
LEFT
JOIN
(SELECT EMBARKED,
COUNT(PASSENGERID) N_PASSENGERS
FROM MYDATA.DATASET4
GROUP
BY 1) B
ON A.EMBARKED = B.EMBARKED
;

-- [그림 8-21 결과]
SELECT BOARDED,
DESTINATION,
COUNT(PASSENGERID) N_PASSENGERS
FROM MYDATA.DATASET4
GROUP
BY BOARDED,
DESTINATION
ORDER
BY 3 DESC
;

-- [그림 8-23 결과]
SELECT *,
ROW_NUMBER() OVER(ORDER BY N_PASSENGERS DESC) RNK
FROM
(SELECT BOARDED,
DESTINATION,
COUNT(PASSENGERID) N_PASSENGERS
FROM MYDATA.DATASET4
GROUP
BY BOARDED,
DESTINATION) BASE
;

-- [265 페이지, 상위 5개 경로]
CREATE TEMPORARY TABLE MYDATA.ROUTE AS
SELECT BOARDED,
DESTINATION
FROM
(SELECT *,
ROW_NUMBER() OVER(ORDER BY N_PASSENGERS DESC) RNK
FROM
(SELECT BOARDED,
DESTINATION,
COUNT(PASSENGERID) N_PASSENGERS
FROM MYDATA.DATASET4
GROUP
BY BOARDED,
DESTINATION) BASE) BASE
WHERE RNK BETWEEN 1 AND 5
;

-- [그림 8-24 결과]
SELECT NAME_WIKI,
A.BOARDED,
A.DESTINATION
FROM MYDATA.DATASET4 A
INNER
JOIN MYDATA.ROUTE B
ON A.BOARDED = B.BOARDED AND A.DESTINATION = B.DESTINATION
;

-- [그림 8-25 결과]
SELECT HOMETOWN,
SUM(1) N_PASSENGERS,
SUM(SURVIVED)/SUM(1) SURVIVED_RATIO
FROM MYDATA.DATASET4
GROUP
BY 1
;

-- [그림 8-26 결과]
SELECT HOMETOWN,
SUM(1) N_PASSENGERS,
SUM(SURVIVED)/SUM(1) SURVIVED_RATIO
FROM MYDATA.DATASET4
GROUP
BY 1
HAVING SUM(SURVIVED)/SUM(1) >= 0.5 AND SUM(1) >= 10
;

